name: Check rust generate
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  check-go-generate:
    name: Check make generate-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.82.0

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Run make generate-rs
        run: make generate-rs

      - name: Check if make generate-rs generated changes that should be committed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: make generate-rs generated changes that should be committed. Please run 'make generate-rs' and commit the changes."
            git diff
            git status
            exit 1
          fi